<?php
  /**
  * @file
  * Contains hello.module.
  */

  use Drupal\Core\Routing\RouteMatchInterface;

  /**
  * Implements hook_help().
  */
  function custom_page_help($route_name, RouteMatchInterface $route_match) {
    switch ($route_name) {
      // Main module help for the custom_page module.
      case 'help.page.hello':
        $output = '';
        $output .= '<h3>' . t('About') . '</h3>';
        $output .= '<p>' . t('My Awesome Module') . '</p>';
        return $output;

      default:
    }
  }
?>